#mybatis:
#  config-location: classpath:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/muke
    username: root
    password: root
  web:
    resources:
      static-locations: classpath:/static/,file:D:/onlineEdu/

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.muke.onlineedu.*.entity