# 开发环境
#mybatis:
#  config-location: classpath:
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/muke
    username: root
    password: 211506164Ding!
  web:
    resources:
      static-locations: classpath:/static/,file:D:/onlineEdu/
  redis:
    host: localhost
    port: 6379
# 数据库映射
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.muke.onlineedu.*.entity

commonconfig:
  url: http://127.0.0.1:8080
  realpath: D:/onlineEdu
  photopathprefix: /upload/photo
  videopathprefix: /upload/video
  filepathprefix: /upload/file

