# 生产环境
#mybatis:
#  config-location: classpath:
server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://121.36.141.65:3306/164office
    username: caramel(SQzOXNDSfDrVvVRAdGUTI/sfAkV3XN+bMYEwBwjRTeSRoQj+zVwGsdkEqPJvPBHH)
    password: caramel(txVHlG5vtWXu0AaPRbx30Z8Vp2CPhWmXwes+Zp0rXzFPBAlghzGffg6t29jxJqae)
  web:
    resources:
      static-locations: classpath:/static/,file:/usr/local/164office/data/upload/

# 数据库映射
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ding.office.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

resourcespathutils:
  url: /api/resources # 需要加上 api ,本地开发测试没有 nginx , nginx 会识别 api 并剔除掉
  realpath: /usr/local/164office/data/upload
  photopathprefix: /photo
  videopathprefix: /video
  audiopathprefix: /audio
  filepathprefix: /file