person:
#  user-name 与 userName 等价
  userName: zhangsan
  boss: true
  birth: 2020/2/20 20:22:22
  age: 11
  pet:
    name: 小p
    weight: 35
#  interests:[篮球,乒乓球,羽毛球]
  interests:
    - 篮球
    - 乒乓球
    - 羽毛球
  animal: [猫,狗]
#  score:{english:30,math:40}
  score:
    english:
      first: 10
      second: 20
    math: [20,30]
  salarys:
    - 1000
    - 2000
  allPets:
    sick:
      - {name: dog1,weight: 21}
      - name: dog2
        weight: 23
    health:
      - {name: cat1,weight: 22}
      - {name: cat2,weight: 43}

#spring:
#  mvc:
#    static-path-pattern: /**
#  web:
#    resources:
#      static-locations: classpath:/public/