# 开发环境
#mybatis:
#  config-location: classpath:
server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hyld
    username: root
    password: root
  web:
    resources:
      static-locations: classpath:/static/,file:D:/onlineEdu/

# 数据库映射
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.muke.onlineedu.*.entity

# 全局变量
commonconfig:
  url: http://127.0.0.1:8090
  realpath: D:/onlineEdu
  photopathprefix: /upload/photo
  videopathprefix: /upload/video
  filepathprefix: /upload/file