# 生产环境
#mybatis:
#  config-location: classpath:
server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://121.36.141.65:3306/hyld
    username: caramel(SQzOXNDSfDrVvVRAdGUTI/sfAkV3XN+bMYEwBwjRTeSRoQj+zVwGsdkEqPJvPBHH)
    password: caramel(txVHlG5vtWXu0AaPRbx30Z8Vp2CPhWmXwes+Zp0rXzFPBAlghzGffg6t29jxJqae)
  web:
    resources:
      static-locations: classpath:/static/,file:/usr/local/hyld/hyldData/upload/

# 数据库映射
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ding.hyld.entity

resourcespathutils:
  url: /api
  realpath: /usr/local/hyld/hyldData/upload
  photopathprefix: /photo
  videopathprefix: /video
  audiopathprefix: /audio
  filepathprefix: /file