export default [
  {
    path:'/',
    name:'Home',
    component:()=>import('@/views/Home.vue')
  },
  {
    path:'/Top',
    name:'Top',
    component:()=>import('@/views/Top.vue')
  },
  {
    path:'/StudentCenter',
    name:'StudentCenter',
    component:()=>import('@/views/StudentCenter.vue')
  },
  {
    path:'/TeacherCenter',
    name:'TeacherCenter',
    component:()=>import('@/views/TeacherCenter.vue')
  },
  {
    path:'/CourseManagement',
    name:'CourseManagement',
    component:()=>import('@/views/CourseManagement.vue')
  },
  {
    path:'/CourseTest',
    name:'CourseTest',
    component:()=>import('@/views/CourseTest.vue')
  },
  {
    path:'/CourseResource',
    name:'CourseResource',
    component:()=>import('@/views/CourseResource.vue')
  },
  {
    path:'/SearchCourse',
    name:'SearchCourse',
    component:()=>import('@/views/SearchCourse.vue')
  },
  {
    path:'/SearchResource',
    name:'SearchResource',
    component:()=>import('@/views/SearchResource.vue')
  },
  {
    path:'/Course',
    name:'Course',
    component:()=>import('@/views/Course.vue')
  },
  {
    path:'/Learn',
    name:'Learn',
    component:()=>import('@/views/Learn.vue')
  },
  {
    path:'/AddCourseResource',
    name:'AddCourseResource',
    component:()=>import('@/views/AddCourseResource.vue')
  },
  {
    path:'/Test',
    name:'Test',
    component:()=>import('@/views/Test.vue')
  },
]
